# Generated by Django 3.2.8 on 2022-02-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nft_article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nft_name', models.CharField(max_length=100)),
                ('designer_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=600)),
                ('nft_image', models.ImageField(upload_to='media')),
                ('published_time', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('url_buy', models.CharField(max_length=400, verbose_name='URL Link (OpenSea , SuperRare , Rarible')),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], max_length=1)),
            ],
        ),
    ]
